/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2018-09-20 03:44:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.note;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class inotecenter_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/D:/Projects/house/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/2-inote/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1477826946715L));
    _jspx_dependants.put("jar:file:/D:/Projects/house/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/2-inote/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("jar:file:/D:/Projects/house/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/2-inote/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153356282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
String basePath = request.getContextPath(); 
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>New_note</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(basePath);
      out.write("/styles/edit.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(basePath);
      out.write("/styles/icon.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(basePath);
      out.write("/styles/prettify.min.css\"/>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<header class='clear_float'>\r\n");
      out.write("\t\t<div class=\"logo\"></div>\r\n");
      out.write("\t\t<div class=\"activity_btn\">\r\n");
      out.write("\t\t\t<div class=\"activity_link\">\r\n");
      out.write("\t\t\t\t<h4><a class=\"ac_link\"  onclick=\"openActivity();\">活动</a><i class='icon i_global'></i></h4>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<div class=\"row clear_float\">\r\n");
      out.write("<!-- alert -->\r\n");
      out.write("\t\t<div class=\"alert_can\" style='display:none;'>\r\n");
      out.write("\t\t\t<div class=\"alert_background\"></div>\r\n");
      out.write("\t\t\t<div class=\"right_bottom\">\r\n");
      out.write("\t\t\t\t<div class=\"panel_can\"><!-- panel容器 -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("<!-- col_1 -->\r\n");
      out.write("\t\t<div class=\"col_1\">\r\n");
      out.write("\t\t\t<div class=\"border\">\r\n");
      out.write("\t\t\t\t<div class=\"col_top clear_float\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col_li li_action\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"addNoteBook\"><i class='icon i_plus'></i></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col_li li_title\">\r\n");
      out.write("\t\t\t\t\t\t<h4 class='text_over'>我的笔记本</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col_middle\" style='/*height:550px;*/'>\r\n");
      out.write("\t\t\t\t\t<ul id='noteBookList'>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col_bottom clear_float\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col_li special\" style='width:33.3%;' id='activityBt'><i class='icon i_action'></i></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col_li special\" style='width:33.4%;' id='starBt'><i class='icon i_star'></i></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col_li special\" style='width:33.3%;' id='recycleBt'><i class='icon i_recycle'></i></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("<!-- col_2 我的笔记-->\r\n");
      out.write("\t\t<div class=\"col_2\"><!-- noteCan -->\r\n");
      out.write("\t\t\t<div class=\"border\">\r\n");
      out.write("\t\t\t\t<div class=\"col_top clear_float\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col_li li_action\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"addNote\"><i class='icon i_plus'></i></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col_li li_title\">\r\n");
      out.write("\t\t\t\t\t\t<h4 class='text_over'>我的笔记</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col_middle\" style='/*height:550px;*/'>\r\n");
      out.write("\t\t\t\t\t<ul id='my_note'><!-- #my_note,#search_note,#recycle_note,#star_note,#activity_note -->\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("<!-- col_3 预览笔记-->\r\n");
      out.write("\t\t<div class=\"col_3\" id='viewNote'>\r\n");
      out.write("\t\t\t<div class=\"note_title clear_float\">\r\n");
      out.write("\t\t\t\t<div class=\"col_li col_left\"><i class='icon i_quoteLeft'></i></div>\r\n");
      out.write("\t\t\t\t<div class=\"col_li col_left\" style='max-width:80%'><h2 class='h2_styles text_over' id='outputNoteTitle'></h2></div>\r\n");
      out.write("\t\t\t\t<div class=\"col_li col_left\"><i class='icon i_quoteRight'></i></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"outputNoteContent\" class=\"note_content\" style='/*height:550px;*/'>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("<!-- col_3 编辑笔记-->\r\n");
      out.write("\t\t<div class=\"col_3\" id='editNote'>\r\n");
      out.write("\t\t\t<div class=\"note_title clear_float\">\r\n");
      out.write("\t\t\t\t<div class=\"col_li col_left\" style='width:79%'><input class='input_text' id='inputNoteTitle' type=\"text\" placeholder=\"此处输入笔记标题\"/></div>\r\n");
      out.write("\t\t\t\t<div class=\"col_li\" style='width:20%'>\r\n");
      out.write("\t\t\t\t\t<!--div class=\"col_li col_left\"-->\r\n");
      out.write("\t\t\t\t\t\t<div id=\"saveNote\">\r\n");
      out.write("\t\t\t\t\t\t\t<p><i class='icon i_save'></i><span class='font_16'>保存&nbsp;</span></p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"note_content\" style='margin:0'>\r\n");
      out.write("\t\t\t\t<form>\r\n");
      out.write("\t\t\t\t\t<textarea id=\"editorNote\" style=\"width:100%;/*height:550px;*/\"></textarea>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t\t<div class=\"alert_success_s\"></div>\r\n");
      out.write("\t\t<div class=\"alert_success_b\"></div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/javascripts/jquery.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/javascripts/jquery.nicescroll.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/javascripts/run_prettify.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/javascripts/Editor/kindeditor-min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/javascripts/Editor/lang/zh_CN.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/javascripts/index.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/javascripts/BaseValues.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" >\r\n");
      out.write("\t/**\r\n");
      out.write("\t\t\t*进入页面之后加载，查询所有笔记\r\n");
      out.write("\t\t\t*/\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\turl : basePath +\"note/getAllNoteBook\",\r\n");
      out.write("\t\t\t\tasync : false,\r\n");
      out.write("\t\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t//alert(data.allNoteBook);\r\n");
      out.write("\t\t\t\t\tif(data.allNoteBook!=null){\r\n");
      out.write("\t\t\t\t\t\tvar allNoteBookList = eval(data.allNoteBook);\r\n");
      out.write("\t\t\t\t\t\t$(\"#recycleBt\").data(\"recycleBtRowKey\",data.recycleBtRowKey);\r\n");
      out.write("\t\t\t\t\t\t$(\"#starBt\").data(\"starBtRowKey\",data.starBtRowKey);\r\n");
      out.write("\t\t\t\t\t\t$(\"#activityBt\").data(\"activityBtRowKey\",data.activityBtRowKey);\r\n");
      out.write("\t\t\t\t\t\t$.each(allNoteBookList,function(idx,item){ //循环对象取值\r\n");
      out.write("\t\t\t\t\t\t\tvar title=addNoteBook(item.name);\r\n");
      out.write("\t\t\t\t\t\t\t$('#noteBookList').prepend(title);\r\n");
      out.write("\t\t\t\t\t\t\t$('#noteBookList li:first').data('noteBookRowKey',item.rowKey);\r\n");
      out.write("\t\t          \t\t });\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror:function(data) {\r\n");
      out.write("\t\t\t\t\talert(\"no\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
