/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2018-09-20 03:44:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class login2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1477826946715L));
    _jspx_dependants.put("jar:file:/D:/Projects/house/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/2-inote/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	String basePath = request.getContextPath();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html class=\"no-js\"><!--<![endif]--><head>\r\n");
      out.write("<meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("        <meta charset=\"utf-8\">\r\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("        <meta name=\"description\" content=\"\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width\">\r\n");
      out.write("        <title>云笔记</title>\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"");
      out.print(basePath);
      out.write("/images/main.css\" type=\"text/css\">\r\n");
      out.write("        <script type=\"text/javascript\">\r\n");
      out.write("function login(){\r\n");
      out.write("\tdocument.getElementById('login_form').submit();\r\n");
      out.write("}\r\n");
      out.write("function refreshMe(obj) {\r\n");
      out.write("\tobj.src = \"http://localhost:8080/ttsweb/verifyCode/getCode.do?t=\" + Math.random();\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body class=\"\">\r\n");
      out.write("    <div class=\"hd\">\r\n");
      out.write("        <div class=\"wrap\">\r\n");
      out.write("            <div class=\"hd-main\">\r\n");
      out.write("            <h1 class=\"logo\"><img src=\"");
      out.print(basePath);
      out.write("/images/663ffc1b.png\" alt=\"云笔记\"></h1>\r\n");
      out.write("            <div class=\"nav\">\r\n");
      out.write("                <a target=\"_blank\" href=\"");
      out.print(basePath);
      out.write("\">首页&nbsp;</a>\r\n");
      out.write("                |\r\n");
      out.write("                <a  href=\"\">&nbsp;多平台下载</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"bd\">\r\n");
      out.write("        <div class=\"bd-login\">\r\n");
      out.write("        <div class=\"bd-login-main\">\r\n");
      out.write("            <div class=\"login-top\">\r\n");
      out.write("                <p>\r\n");
      out.write("                    <span id=\"invite-name\"></span>\r\n");
      out.write("                    &nbsp;\r\n");
      out.write("                </p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <form class=\"login-left\"  action=\"");
      out.print(basePath);
      out.write("/login/loginnow\" method=\"post\" id =\"login_form\">\r\n");
      out.write("                <h2>账号登录：</h2>\r\n");
      out.write("                <div class=\"row text-row\">\r\n");
      out.write("                    <input name=\"loginName\" id=\"login_name\" placeholder=\"账号\" data-node=\"loginUser\" class=\"login-username text\" type=\"text\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row text-row\">\r\n");
      out.write("                    <input name=\"password\" id=\"login_password\" placeholder=\"密码\" data-node=\"loginPwd\" class=\"login-password text\" type=\"password\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row check-row\">\r\n");
      out.write("                    <label class=\"login-label\"><input  class=\"login-checkbox\" type=\"CHECKBOX\">自动登录</label>\r\n");
      out.write("                    <span data-node=\"loginError\" class=\"login-error\">输入的账号或密码有误</span>\r\n");
      out.write("                    <a class=\"login-nopassword\" >忘记密码?</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row row-btn\">\r\n");
      out.write("                    <input name=\"提交\" data-node=\"loginSubmit\" class=\"login-btn btn\" value=\"\" type=\"submit\" onclick=\"login()\">\r\n");
      out.write("                    <input  target=\"_blank\" data-node=\"loginRegist\" class=\"login-btn btn2\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("            <div class=\"login-middle\"></div>\r\n");
      out.write("            <div class=\"login-right\">\r\n");
      out.write("                <h2>其他账号登录：</h2>\r\n");
      out.write("                <div class=\"row-btn\">\r\n");
      out.write("                    <span class=\"sina-btn btn2\" >\r\n");
      out.write("                    </span>\r\n");
      out.write("                    <span class=\"qq-btn btn2\" >\r\n");
      out.write("                    </span>\r\n");
      out.write("                    <span class=\"tqq-btn btn2\" >\r\n");
      out.write("                    </span>\r\n");
      out.write("                    <span class=\"hw-btn btn2\" >\r\n");
      out.write("                    </span>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"bd-feture\">\r\n");
      out.write("            <div class=\"bd-feture-main\">\r\n");
      out.write("                <img src=\"");
      out.print(basePath);
      out.write("/images/a88d3aa3.png\" alt=\"随时记录 随时同步\">\r\n");
      out.write("                <img src=\"");
      out.print(basePath);
      out.write("/images/964b896a.png\" alt=\"云端备份 安全可靠\">\r\n");
      out.write("                <img src=\"");
      out.print(basePath);
      out.write("/images/72297351.png\" alt=\"为中国用户贴心设计\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"ft\">\r\n");
      out.write("        <div class=\"ft-nav\">\r\n");
      out.write("           <span></span>\r\n");
      out.write("           <a  关于></a>\r\n");
      out.write("           <a >| 推广</a>\r\n");
      out.write("           <a >| 官方博客</a>\r\n");
      out.write("           <a >| 技术博客</a>\r\n");
      out.write("           <a >| 诚聘英才</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"");
      out.print(basePath);
      out.write("/javascripts/5c4da2bd.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div><div id=\"passportusernamelist\" class=\"domainSelector\" style=\"display: none;\"><table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">       <tbody><tr><td class=\"title\">请选择或继续输入...</td></tr>    <tr><td>&nbsp;</td></tr></tbody></table></div></div></body></html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
