/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2018-09-20 03:26:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1477826946715L));
    _jspx_dependants.put("jar:file:/D:/Projects/house/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/2-inote/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	String basePath = request.getContextPath();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<title>云笔记</title>\r\n");
      out.write("<meta name=\"keywords\"\r\n");
      out.write("\tcontent=\"云笔记 - 记录，成为更好的自己, , office, 办公软件, 云笔记, 印象笔记, 笔记, tower, 云笔记, 笔记, 团队协作, 协作, etc.\">\r\n");
      out.write("<meta name=\"description\"\r\n");
      out.write("\tcontent=\"云笔记是个人与团队的线上资料库，信息全平台覆盖， 随时随地、随心访问所有资料。团队成员在这里高效协作，无缝沟通。网易出品，安全可靠。2500万用户的选择。\">\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(basePath);
      out.write("/styles/7ac21bf4.css\">\r\n");
      out.write("<script src=\"");
      out.print(basePath);
      out.write("/javascripts/rlog.js\" async=\"\"\r\n");
      out.write("\ttype=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"");
      out.print(basePath);
      out.write("/javascripts/67b4ad50.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"header\">\r\n");
      out.write("\t\t<div id=\"header-warp\">\r\n");
      out.write("\t\t\t<div id=\"header-right\">\r\n");
      out.write("\t\t\t\t<a id=\"register\" href=\"\">注册</a>\r\n");
      out.write("\t\t\t\t<div id=\"user-info\">\r\n");
      out.write("\t\t\t\t\t<span id=\"dropdown-button\">登录网页版</span> <i id=\"dropdown\"></i>\r\n");
      out.write("\t\t\t\t\t<ul id=\"dropdown-list\">\r\n");
      out.write("\t\t\t\t\t\t<li id=\"web1\"><a id=\"web-title2\">登录云笔记</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"divider\"><a></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li ><a >下载</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"divider\" id=\"logout-divider\"><a></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li id=\"logout\"><a>注销</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<a id=\"logo\"  title=\"云笔记\"></a>\r\n");
      out.write("\t\t\t<ul id=\"header-nav\">\r\n");
      out.write("\t\t\t\t<li class=\"nav-current\" id=\"index-tab\"><a\r\n");
      out.write("\t\t\t\t\t>首页</a></li>\r\n");
      out.write("\t\t\t\t<li id=\"noteintro-tab\"><a target=\"_blank\" href=\"http://192.168.0.220:8081/inote/login/showloginpage3\"\r\n");
      out.write("\t\t\t\t\t>云笔记</a></li>\r\n");
      out.write("\t\t\t\t<li id=\"groupintro-tab\"><a\r\n");
      out.write("\t\t\t\t\t>云协作</a></li>\r\n");
      out.write("\t\t\t\t<li id=\"download-tab\"><a\r\n");
      out.write("\t\t\t\t\t>下载</a></li>\r\n");
      out.write("\t\t\t\t<li id=\"blog-tab\"><a >博客</a></li>\r\n");
      out.write("\t\t\t\t<li id=\"charge-tab\"><a\r\n");
      out.write("\t\t\t\t\t>会员</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"doc2\">\r\n");
      out.write("\t\t<div id=\"hd\">\r\n");
      out.write("\t\t\t<div class=\"bd-wrap\">\r\n");
      out.write("\t\t\t\t<div class=\"bd\">\r\n");
      out.write("\t\t\t\t\t<div class=\"slogan\"></div>\r\n");
      out.write("\t\t\t\t\t<div id=\"download-btn-container\">\r\n");
      out.write("\t\t\t\t\t\t<a data-vlog=\"/sd_index.v\"\r\n");
      out.write("\t\t\t\t\t\t\thref=\"http://download.ydstatic.com/notewebsite/downloads/YNote.exe\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"download-btn\" class=\"logit ynote-download\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-logname=\"index.windowsBanner.download-btn-windows\"></a>\r\n");
      out.write("\t\t\t\t\t\t<div style=\"width: 140px;\" id=\"ynote-version\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"fixed-bottom\" id=\"download-bar\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"download-bar-list\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"windows-download\"><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"http://download.ydstatic.com/notewebsite/downloads/YNote.exe\"></a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"mac-download\"><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"https://itunes.apple.com/cn/app/youdao-note/id692678875?ls=1&amp;mt=12\"></a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"android-download\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"download-bar-sub\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"btn-normal\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"download-qrcode\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"");
      out.print(basePath);
      out.write("/images/84f03692.png\" alt=\"二维码下载\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"btn-normal\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t>本地下载</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"iphone-download\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"download-bar-sub\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"btn-normal\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t二维码下载\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"download-qrcode\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"");
      out.print(basePath);
      out.write("/images/84f03692.png\" alt=\"二维码下载\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"btn-normal\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t>App\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tStore下载</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"ipad-download\"><a\r\n");
      out.write("\t\t\t\t\t\t\t></a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"bd\" class=\"clearfix\">\r\n");
      out.write("\t\t\t<ul class=\"intros\">\r\n");
      out.write("\t\t\t\t<li><a class=\"btn-video-play cboxElement\">\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"");
      out.print(basePath);
      out.write("/images/a1a70e40.png\" alt=\"一分钟快速认识云协作\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"");
      out.print(basePath);
      out.write("/images/71fec3d9.png\" alt=\"play\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"video-play\"><span class=\"intro-desc\"><p>一分钟，快速认识云协作</p></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</a> <a ><span\r\n");
      out.write("\t\t\t\t\t\tclass=\"intro-more\">更多视频 &gt;</span></a></li>\r\n");
      out.write("\t\t\t\t<li class=\"intro-platform\">\r\n");
      out.write("\t\t\t\t\t <a\t\t\t\t\t>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"");
      out.print(basePath);
      out.write("/images/20f4ba23.png\" alt=\"云协作企业版\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"intro-desc\"><p>云协作企业版，来了！</p></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</a> <a ><span\r\n");
      out.write("\t\t\t\t\t\tclass=\"intro-more\">更多产品动态 &gt;</span></a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<img src=\"");
      out.print(basePath);
      out.write("/images/02e7cce7.png\" alt=\"AppStore精选效率APP\">\r\n");
      out.write("\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"footer\">\r\n");
      out.write("\t\t\t<ul id=\"ft-follow-us\">\r\n");
      out.write("\t\t\t\t<li><a href=\"http://weibo.com/youdaonote\" id=\"weibo\"\r\n");
      out.write("\t\t\t\t\ttarget=\"_blank\"></a></li>\r\n");
      out.write("\t\t\t\t<li><a id=\"wechat\"><img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"");
      out.print(basePath);
      out.write("/images/e5ea2639.png\"></a></li>\r\n");
      out.write("\t\t\t\t<li><a id=\"qq\"><img src=\"");
      out.print(basePath);
      out.write("/images/d984692a.png\"></a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<ul id=\"ft-links\">\r\n");
      out.write("\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\ttarget=\"_blank\">官方贴吧</a></li> ·\r\n");
      out.write("\t\t\t\t<li><a \r\n");
      out.write("\t\t\t\t\ttarget=\"_blank\">空间兑换</a></li> ·\r\n");
      out.write("\t\t\t\t<li><a >开放平台</a></li>\r\n");
      out.write("\t\t\t\t·\r\n");
      out.write("\t\t\t\t<li><a  target=\"_blank\">云协作企业版</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<ul id=\"ft-about-links\">\r\n");
      out.write("\t\t\t\t<li><a \r\n");
      out.write("\t\t\t\t\ttarget=\"_blank\">关于我们</a></li> |\r\n");
      out.write("\t\t\t\t<li><a \r\n");
      out.write("\t\t\t\t\ttarget=\"_blank\">联系我们</a></li> |\r\n");
      out.write("\t\t\t\t<li><a \r\n");
      out.write("\t\t\t\t\ttarget=\"_blank\">服务条款</a></li> |\r\n");
      out.write("\t\t\t\t<li><a \r\n");
      out.write("\t\t\t\t\ttarget=\"_blank\">隐私协议</a></li> |\r\n");
      out.write("\t\t\t\t<li><a \r\n");
      out.write("\t\t\t\t\ttarget=\"_blank\">帮助</a></li> |\r\n");
      out.write("\t\t\t\t<li><a \r\n");
      out.write("\t\t\t\t\ttarget=\"_blank\">更新日志</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<div id=\"copyright\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"dialog-mask\"></div>\r\n");
      out.write("\t<div style=\"display: none;\" id=\"cboxOverlay\"></div>\r\n");
      out.write("\t<div style=\"display: none;\" tabindex=\"-1\" role=\"dialog\" class=\"\"\r\n");
      out.write("\t\tid=\"colorbox\">\r\n");
      out.write("\t\t<div id=\"cboxWrapper\">\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<div style=\"float: left;\" id=\"cboxTopLeft\"></div>\r\n");
      out.write("\t\t\t\t<div style=\"float: left;\" id=\"cboxTopCenter\"></div>\r\n");
      out.write("\t\t\t\t<div style=\"float: left;\" id=\"cboxTopRight\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"clear: left;\">\r\n");
      out.write("\t\t\t\t<div style=\"float: left;\" id=\"cboxMiddleLeft\"></div>\r\n");
      out.write("\t\t\t\t<div style=\"float: left;\" id=\"cboxContent\">\r\n");
      out.write("\t\t\t\t\t<div style=\"float: left;\" id=\"cboxTitle\"></div>\r\n");
      out.write("\t\t\t\t\t<div style=\"float: left;\" id=\"cboxCurrent\"></div>\r\n");
      out.write("\t\t\t\t\t<button id=\"cboxPrevious\" type=\"button\"></button>\r\n");
      out.write("\t\t\t\t\t<button id=\"cboxNext\" type=\"button\"></button>\r\n");
      out.write("\t\t\t\t\t<button id=\"cboxSlideshow\"></button>\r\n");
      out.write("\t\t\t\t\t<div style=\"float: left;\" id=\"cboxLoadingOverlay\"></div>\r\n");
      out.write("\t\t\t\t\t<div style=\"float: left;\" id=\"cboxLoadingGraphic\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div style=\"float: left;\" id=\"cboxMiddleRight\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"clear: left;\">\r\n");
      out.write("\t\t\t\t<div style=\"float: left;\" id=\"cboxBottomLeft\"></div>\r\n");
      out.write("\t\t\t\t<div style=\"float: left;\" id=\"cboxBottomCenter\"></div>\r\n");
      out.write("\t\t\t\t<div style=\"float: left;\" id=\"cboxBottomRight\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div\r\n");
      out.write("\t\t\tstyle=\"position: absolute; width: 9999px; visibility: hidden; display: none; max-width: none;\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(\"#web-title2\").click(function(){\r\n");
      out.write("\t\tlocation.href = \"");
      out.print(request.getContextPath());
      out.write("/login/showloginpage2\";\r\n");
      out.write("})\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
